[package]
name = "enum_index_types"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1" }
syn = { version = "2", features = ["derive",] }
thiserror = "1"
